### ISSUE TITLE
Is there a way that I can customize the source/sink list, and then parse the list while running Amandroid?

### ISSUE THREAD

**Issue by LinaQiu** [arguslab/Argus-SAF#11]
Hey, 

I read your paper Amandroid (the one that is published on CCS, 2014), and in the paper, the authors mentioned that analysts can customize their source and sink list themselves. I then tried to run your tool (`argus-saf_2.12-3.1.1-assembly.jar`) with command suggested in issue #5 , and it works perfect. I just wonder whether you could help point out how should I customize the source/sink list exactly? How does the customization work actually? Any suggestions would be very helpful! Thanks in advance!

Best Regards

**Comment by fgwei** [comment]
In short you can add you customized list at file:
~/.amandroid_stash/amandroid/taintAnalysis/sourceAndSinks/TaintSourcesAndSinks.txt

You can also modify line "sas_file=/your/sas/file/path" at
~/.amandroid_stash/amandroid/config.ini to point to your own sas_file.

For some information of how Source and Sink manager work you can check:
http://pag.arguslab.org/argus-saf#tutorial-taint-ssm

**Comment by LinaQiu** [comment]
Thanks! It is very helpful!
