### ISSUE TITLE
ExplicitValueFinder

### ISSUE THREAD

**Issue by mkucijan** [arguslab/Argus-SAF#12]
Hi, i was trying out your analyzer for detecting cryptograpfic misuse and wanted to use ExplicitValueFinder to check some other methods too so i did some testing and found that ExplicitValueFinder has problems detecting that i use ECB mode or constant IV when im passing them as arguments to the function.

**Comment by fgwei** [comment]
Yes, the ExplicitValueFinder is for intra-procedural use only.
If you want to track inter-procedural values, use data-flow analysis.

**Comment by mkucijan** [comment]
Could u point me to the modules that can help me accomplish that?

**Comment by fgwei** [comment]
This link might help you to understand how to retrieve values from data-flow analysis:
https://github.com/arguslab/Argus-SAF-playground/blob/master/src/main/scala/org/argus/play/random/RetriveStringFromSourceOrSink.scala

**Comment by mkucijan** [comment]
thanks you for providing the example, but how do i resolve defsite when its out of the scope of the method and the value is passed as an argument, for example if the url was passed as an argument to the get() method

**Comment by fgwei** [comment]
The data flow is inter-procedural, so if its a string defined in another method and passed to this one, the context of defsite will be the creation site of such string.

**Comment by mkucijan** [comment]
Ye sorry. i thought defsite wasnt returning me the location. Im closing this, thanks.
