### ISSUE TITLE
Explicit Value Finder (2)

### ISSUE THREAD

**Issue by wonupbi** [arguslab/Argus-SAF#13]
According to the 1st 'ExplicitValueFinder', I can understand how to get String values.

However, in case of other values such as file object, how can I extract that value? 

I'm trying to change PTA instances but only string values can be extracted by PTAConcreteStringInstance as I understand.

Thank you.

**Comment by fgwei** [comment]
Other instance contains the object type and defsite, only string value can be extracted from PTAConcreteStringInstance. What else value you want to extract?

**Comment by wonupbi** [comment]
For example, I want to get a file path from FileOutputStream;.<init>:(Ljava/lang/String).

In a case that the String value is given "/sdcard/Downloads", I can retrieve the path value.

However, in a case that the String value is given "android.os.Environment.DIRECTORY_DOWNLOADS" of which value is equal to "/sdcard/Downloads" and return type is also String, I cannot retrieve the value.

I wonder that how I can retrieve such value, thank you.

**Comment by fgwei** [comment]
android.os.Environment.DIRECTORY_DOWNLOADS is a global (static) variable.
From bytecode you can only see something equal to this global variable, and the value of the variable is initiated at the framework code which is not obtainable.

One possible solution is to build a global variable value mapping before hand, then when you see a global variable read in the code, you can lookup the map to find its value.
