### ISSUE TITLE
 The meaning of the taint path result  and How to find the function with it.

### ISSUE THREAD

**Issue by TONGZHU95** [arguslab/Argus-SAF#15]
i am a newcomer to the amandroid and i have used it to get the taint analysis result.could you please tell me the meaning of the taint path in its result (i mean the string like"L0cd1e0",the relation between "(cx.a,L0c75ec)"and "(dp.a,L0cd1e0)"in " VirtualBody@(cx.a,L0c75ec)(dp.a,L0cd1e0)" and the meaning of "->").And how can i exactly find the function which has used the function in the Sink according to the taint path result ?

TaintPath:
      Source: <Descriptors: api_source: Lorg/apache/http/HttpResponse;.getEntity:()Lorg/apache/http/HttpEntity; >
      Sink: <Descriptors: api_sink: Ljava/io/FileOutputStream;.write:([BII)V 1>
      Types: maliciousness:information_theft
      The path consists of the following edges ("->"). The nodes have the context information (p1 to pn means which parameter). The source is at the top :
        VirtualBody@(cx.a,L0c75ec)(dp.a,L0cd1e0)  ->
        Call@(cx.a,L0c75fc)(dp.a,L0cd1e0)p1  ->
        VirtualBody@(cx.a,L0c79b2)(cy.run,L0c870c)

Best Regards

**Comment by fgwei** [comment]
(cx.a,L0c75ec) means 
class: cx 
method: a 
location: L0c75ec (This location is present in the .jawa file)
(cx.a,L0c75ec)(dp.a,L0cd1e0) means: one level of calling context, the cx.a() is called from dp.a at location L0cd1e0.
VirtualBody means the instruction at (cx.a,L0c75ec) is a modeled function call.

So to interpret your path:
1. get source at modeled function call: VirtualBody@(cx.a,L0c75ec)(dp.a,L0cd1e0)
2. the data is flow to the first parameter (p1) of method call: Call@(cx.a,L0c75fc)(dp.a,L0cd1e0).
3. the data reached a sink at modeled function call: VirtualBody@(cx.a,L0c79b2)(cy.run,L0c870c)

**Comment by TONGZHU95** [comment]
OK i got it.Thank you very much!

**Comment by aishwaryakarad** [comment]
This is the output I got for one of my apks and after reading the answer above it was de-mystified a little but I still don't understand what is happening.
Thank you.


TaintPath:
      Source: <Descriptors: api_source: Landroid/app/PendingIntent;.getActivity:(Landroid/content/Context;ILandroid/content/Intent;I)Landroid/app/PendingIntent;>
      Sink: <Descriptors: api_sink: Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2>
      Types: maliciousness:information_theft
      The path consists of the following edges ("->"). The nodes have the context information (p1 to pn means which parameter). The source is at the top :
        List(#L48ffc6.  call temp:= `getActivity`(v3, v4, v0, v1) @signature `Landroid/app/PendingIntent;.getActivity:(Landroid/content/Context;ILandroid/content/Intent;I)Landroid/app/PendingIntent;` @kind static;, #L48fb88.  call temp:= `append`(v0, v1) @signature `Ljava/lang/StringBuilder;.append:(Ljava/lang/Object;)Ljava/lang/StringBuilder;` @kind virtual;, #L48fb98.  call temp:= `toString`(v0) @signature `Ljava/lang/StringBuilder;.toString:()Ljava/lang/String;` @kind virtual; param: 0, #L48fb98.  call temp:= `toString`(v0) @signature `Ljava/lang/StringBuilder;.toString:()Ljava/lang/String;` @kind virtual;, #L48fb9e.  v0:= temp @kind object;, #L48fba0.  return v0 @kind object;, #L48f970.  call temp:= `toString`(v6) @signature `Ltunein/leanback/RecommendationBuilder;.toString:()Ljava/lang/String;` @kind virtual;, #L48f976.  v2:= temp @kind object;, #L48f978.  call temp:= `append`(v1, v2) @signature `Ljava/lang/StringBuilder;.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;` @kind virtual; param: 1, #L48f978.  call temp:= `append`(v1, v2) @signature `Ljava/lang/StringBuilder;.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;` @kind virtual;, #L48f97e.  call temp:= `toString`(v1) @signature `Ljava/lang/StringBuilder;.toString:()Ljava/lang/String;` @kind virtual; param: 0, #L48f97e.  call temp:= `toString`(v1) @signature `Ljava/lang/StringBuilder;.toString:()Ljava/lang/String;` @kind virtual;, #L48f984.  v1:= temp @kind object;, #L48f986.  call temp:= `d`(v0, v1) @signature `Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I` @kind static; param: 2)
