### ISSUE TITLE
The .jawa file in amandroid

### ISSUE THREAD

**Issue by TONGZHU95** [arguslab/Argus-SAF#17]
I have another problem.The lines below are the lines in the .jawa file according to the taint path result:

taint path:VirtualBody@(cx.a,L0c75ec)(dp.a,L0cd1e0)->

#L0c75ec.  call temp:=  `java.io.InputStream.read`(v3, v0) @signature `Ljava/io/InputStream;.read:([B)I` @classDescriptor ^`java.io.InputStream` @kind virtual;
#L0cd1e0.  call `com.fortumo.android.dp.a`(v1, v0) @signature `Lcom/fortumo/android/dp;.a:(Ljava/io/InputStream;Ljava/io/OutputStream;)V` @classDescriptor ^`com.fortumo.android.dp` @kind static;

taint path:Call@(cx.a,L0c75fc)(dp.a,L0cd1e0)p1->

#L0c75fc.  call `java.io.OutputStream.write`(v4, v0, v2, v1) @signature `Ljava/io/OutputStream;.write:([BII)V` @classDescriptor ^`java.io.OutputStream` @kind virtual;
#L0cd1e0.  call `com.fortumo.android.dp.a`(v1, v0) @signature `Lcom/fortumo/android/dp;.a:(Ljava/io/InputStream;Ljava/io/OutputStream;)V` @classDescriptor ^`com.fortumo.android.dp` @kind static;

taint path:VirtualBody@(cx.a,L0c79b2)(cy.run,L0c870c)

#L0c79b2.  call temp:=  `org.apache.http.HttpResponse.getEntity`(v3) @signature `Lorg/apache/http/HttpResponse;.getEntity:()Lorg/apache/http/HttpEntity;` @classDescriptor ^`org.apache.http.HttpResponse` @kind interface;
#L0c870c.  call temp:=  `com.fortumo.android.cx.a`(v0, v1) @signature `Lcom/fortumo/android/cx;.a:(Lcom/fortumo/android/da;)Lcom/fortumo/android/db;` @classDescriptor ^`com.fortumo.android.cx` @kind virtual;

There are some problems:
1.My apk is obfuscated and there are some method which have the same name in one class just like
"public class cx
{
protected static void a(InputStream paramInputStream, OutputStream paramOutputStream)
  {
   ...  }
 protected final String a(String[] paramArrayOfString)
  {
    ...}
protected void a(db paramdb)
  {
  ...}
}
"
And how can I know which method shoud I find according to the result?

2.What's the meaning of the lines in the .jawa files,I cannot understand what it exactly mean.

I am a newcomer to the amandroid so there are a little bit more problems for me and I hope for your guide.

Best Regards

**Comment by fgwei** [comment]
This is the signature:
Lcom/fortumo/android/dp;.a:(Ljava/io/InputStream;Ljava/io/OutputStream;)V

It's the method "a" in class "dp" with two params, param types are:
1. java.io.InputStream
2. java.io.OutputStream
and with return type:
void

Then you can go to use the signature to find corresponding method in jawa:
protected static void a(InputStream paramInputStream, OutputStream paramOutputStream)
{
... 
}

**Comment by TONGZHU95** [comment]
And in the txt below:

taint path:Call@(cx.a,L0c75fc)(dp.a,L0cd1e0)p1->
#L0c75fc. call java.io.OutputStream.write(v4, v0, v2, v1) @Signature Ljava/io/OutputStream;.write:([BII)V @classdescriptor ^java.io.OutputStream @kind virtual;
#L0cd1e0. call com.fortumo.android.dp.a(v1, v0) @Signature Lcom/fortumo/android/dp;.a:(Ljava/io/InputStream;Ljava/io/OutputStream;)V @classdescriptor ^com.fortumo.android.dp @kind static;

What's the relationship between "cx.a" and "Ljava/io/OutputStream;.write:([BII)V "?Because the "@classdescriptor " is "java.io.OutputStream " and the class in "cx.a" is "cx",so I don't understand it.

And what's the meaning of ":([BII)" in "@Signature Ljava/io/OutputStream;.write:([BII)V "?

Best Regards

**Comment by TONGZHU95** [comment]
Hi,
Could you please help me to solve my problem?
Best wishes .

**Comment by fgwei** [comment]
(cx.a, L0c75fc) means location L0c75fc in the method a of class cx.
At this location of cx.a invokes a method OutputStream.write().

[BII means signatures of three parameters: (byte[], int, int)
You can check: http://ftp.magicsoftware.com/www/help/mg9/How/howto_java_vm_type_signatures.htm

**Comment by TONGZHU95** [comment]
Thank you very much
