### ISSUE TITLE
amandroid api

### ISSUE THREAD

**Issue by TONGZHU95** [arguslab/Argus-SAF#18]
Hey:
       I want to use amandroid's api to do some analysis.How can i find amandroid's api code and to invoke them?Do I have to use scala and sbt to make a plugin?
Best regard.

**Comment by fgwei** [comment]
You might take a look at:
https://github.com/arguslab/Argus-SAF-playground
to start any project with amandroid.

You can use sbt, maven, gradle to make the project (sbt is preferable).
You can use scala, java to write your code.

**Comment by TONGZHU95** [comment]
Thank you very much.
