### ISSUE TITLE
callMap always empty

### ISSUE THREAD

**Issue by windflyer** [arguslab/Argus-SAF#3]
def outputCallGraph(idfg: InterproceduralDataFlowGraph) = {
        val cg = idfg.icfg.getCallGraph
        if (cg != null) {
            println(cg.getCallMap)
        }
    }

`idfg` is built from each app component, but the output is 

    Map()

**Comment by fgwei** [comment]
Have you build the idfg properly? Could you show me your code?

**Comment by windflyer** [comment]
My bad. I built IDFG in a wrong way...
