### ISSUE TITLE
What would the best way to track an object?

### ISSUE THREAD

**Issue by beumjincho** [arguslab/Argus-SAF#35]
Hi,
I want to track how a given object is used.

file = new File("C:/myfile.txt");

fos = new FileOutputStream(file);
if (!file.exists()) {
   file.createNewFile();
}
byte[] bytesArray = mycontent.getBytes();

fos.write(bytesArray);

For example, once I capture new File(Ljava/lang/String;)V, how can I track its usage throughout the program? In specific, I need to know the file object is used by fileOutputStream. And, the fos eventually invokes write function.

(I tried to use AndroidDataDependantTaintAnalysis. However, since the new statement has no explicit return value, It was impossible.)

**Comment by fgwei** [comment]
You can first build IDFG. And find the interesting node like: Ljava/io/FileOutputStream;.<init>:(Ljava/io/File;)V. Query the instances for the first param, and you will get the file instance used here.

One example you can find here: https://github.com/arguslab/Argus-SAF-playground/blob/master/src/main/scala/org/argus/play/random/RetriveStringFromSourceOrSink.scala

**Comment by beumjincho** [comment]
Thank you for the answer.

Ok, I now understand how the backward tracking works.

How about the "fos.write(bytesArray);" case.
In other words, how can I track the fos object since its initialization, so that later I can know the object is used to call the write function?

**Comment by fgwei** [comment]
fos = new FileOutputStream(file);
actually consists of two steps:
L1. fos = new FileOutputStream;
L2. FileOutputStream.<init>(fos, file);

You can track L2 and build a map:
FileOutputStream@L1 -> file.

Later when you see:
fos.write(bytesArray);

You can check the fos instance (It must be FileOutputStream@L1), and then query the map to find the corresponding file.

**Comment by bj3680** [comment]
Thank you for the help.

I am going to try what you advised.

If I got more question on this, I am going to ask again.
