### ISSUE TITLE
Not able to get instances of params of certain APIs

### ISSUE THREAD

**Issue by bj3680** [arguslab/Argus-SAF#36]
**I want to know the path given by the following code will be "/sdcard/Download/".**

File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);

**And, the code consists of the following two steps in IR.**

L1, v1:= `@@android.os.Environment.DIRECTORY_DOWNLOADS`  @kind object @type ^`java.lang.String`;
L2, call temp:=  `android.os.Environment.getExternalStoragePublicDirectory`(v1) @signature `Landroid/os/Environment;.getExternalStoragePublicDirectory:

**To get the instance of the first param of getExternalStoragePublicDirectory, I tried the blow code.**

   idfg.icfg.nodes foreach {
      case cn: ICFGCallNode if cn.getCalleeSig == new Signature("Landroid/os/Environment;.getExternalStoragePublicDirectory:(Ljava/lang/String;)Ljava/io/File;") =>
        val strSlot = VarSlot(cn.argNames.head, isBase = false, isArg = true)
        val strvalues = idfg.ptaresult.pointsToSet(strSlot, cn.getContext)
        println(strvalues.mkString)
      case _ =>
    }

**However, strvalues is empty. Therefore, I cannot find Environment.DIRECTORY_DOWNLOADS.
How can I solve this issue?
Thanks!**

**Comment by fgwei** [comment]
You can get the new Argus-SAF-playground and give another try. It's might be a bug I fixed last night.

**Comment by bj3680** [comment]
I checked the update.

Thank you for the quick response.
