### ISSUE TITLE
apk.model.getReachableMap is gone

### ISSUE THREAD

**Issue by bj3680** [arguslab/Argus-SAF#39]
Until 3.1.1, I had used apk.model.getReachableMap to get reachable methods to find only interesting components before getting into deeper analysis.

However, it seems that it's gone in 3.1.2.

Is there any other method to do the same?

**Comment by fgwei** [comment]
ReachabilityAnalysis.scala is the file to do reachability analysis. 
You can use: ReachabilityAnalysis.getReachableMethodsBySBCG(global, types)
to do get the reachable method set for given class types.

**Comment by bj3680** [comment]
Thank you, your answer was very helpful!
