### ISSUE TITLE
Running Amandroid

### ISSUE THREAD

**Issue by younkyul** [arguslab/Argus-SAF#4]
I followed the instruction to install Sireum and run Amandroid as stated.
I brought some errors as follows. Can you help me the resolve this issue?

youn@ubuntu:~/Desktop/Sireum$ ./sireum amandroid taintAnalysis -m 4 -o ~/Desktop/Sireum/outputPath ~/Desktop/Sireum/apps/amandroid/sources/icc-bench
Total apks: 19
Analyzing #1:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccTargetFinding/InterComponentCommunication_DynRegister1.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #2:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccHandling/ICC_Implicit_Src_Sink.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #3:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccTargetFinding/InterComponentCommunication_DynRegister2.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #4:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccHandling/ICC_Explicit_NoSrc_NoSink.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #5:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccTargetFinding/InterComponentCommunication_Implicit5.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #6:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccTargetFinding/InterComponentCommunication_Implicit2.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #7:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccHandling/ICC_Implicit_Src_NoSink.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #8:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccTargetFinding/InterComponentCommunication_Implicit3.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #9:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccTargetFinding/InterComponentCommunication_Implicit6.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #10:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccHandling/ICC_Explicit_NoSrc_Sink.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #11:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccHandling/ICC_Implicit_NoSrc_NoSink.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #12:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccTargetFinding/InterComponentCommunication_Explicit1.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #13:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccHandling/ICC_Implicit_NoSrc_Sink.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #14:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccTargetFinding/InterComponentCommunication_Implicit4.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #15:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/FieldAndObjectSensitivity/FieldAndObjectSensitivity_FieldFlowSensitivity1.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #16:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccHandling/ICC_Explicit_Src_Sink.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #17:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccTargetFinding/InterComponentCommunication_Implicit1.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #18:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/AndroidSpecific/AndroidSpecific_PrivateDataLeak3.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog
Analyzing #19:file:/home/youn/Desktop/Sireum/apps/amandroid/sources/icc-bench/IccHandling/ICC_Explicit_Src_NoSink.apk

Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
Written: /home/youn/Desktop/Sireum/outputPath/.errorlog

**Comment by fgwei** [comment]
Plz follow the argus-saf read me:
https://github.com/arguslab/Argus-SAF/blob/master/README.md

Amandroid is no longer maintained.
