### ISSUE TITLE
Fileresolver.scala cannot resolve all string variable.

### ISSUE THREAD

**Issue by TONGZHU95** [arguslab/Argus-SAF#41]
For a testing code:
File file = new File("a"+"b"+"c")
In the old version,it can get all the string values by following scala code:
val strSlot = VarSlot(cn.argNames(1), isBase = false, isArg = true)
val urlvalues = idfg.ptaresult.pointsToSet(strSlot, cn.getContext)
In the urlvalues,there are three string values.But in the latest version,it only can get one string value in urlvalues .

**Comment by fgwei** [comment]
I will push the fix soon.
