### ISSUE TITLE
ICC links from CLI tool

### ISSUE THREAD

**Issue by mehrant95** [arguslab/Argus-SAF#61]
I tried to extract ICC links from an [APK](https://drive.google.com/file/d/1Os3iEG8sc9paHaOxxqIZgoCzb-no6XeQ/view?usp=drive_web) (from [this issue](https://github.com/arguslab/Argus-SAF/issues/53)) using the following command (using java 1.8, ubuntu 16.04):
java -jar argus-saf_2.12-3.2.0-assembly.jar t -o .
But there is no ICC link in the result file, [AppData.txt](https://drive.google.com/open?id=1kbsSNAXT9KGD-FKuTcaeuscYldbAt2Yb) (which is inside result folder). What is wrong with the above command? 
As a side question, is there any more efficient CLI command for just extracting ICC links or i should write some code like [this](https://github.com/arguslab/Argus-SAF/issues/45) ? Because it seems that using `taint` option is doing something more that just extracting ICC links.

**Comment by fgwei** [comment]
That command is running the taint analysis.
If you want to generate the ICC result only, you can follow #45
