### ISSUE TITLE
Cannot get the inner class CFG from Amandroid

### ISSUE THREAD

**Issue by 99zikke** [arguslab/Argus-SAF#67]
I have tried to get the CFG of the codes below. But Amandroid can only get the CFG of outer calss. 

```
public class MyHandler extends Handler {
        public MyHandler(Looper looper) {
            super(looper);
        }

        public void handleMessage(Message msg) {
            ......
        }
    }
```

My codes used to get the CGF are as below which is similar to you example.

```
val ep = apk.getMethod(esig).get
        val initialfacts = AndroidReachingFactsAnalysisConfig.getInitialFactsForMainEnvironment(ep)
        val icfg = new InterProceduralControlFlowGraph[ICFGNode]
        val ptaresult = new PTAResult
        val sp = new AndroidSummaryProvider(apk)
        val analysis = new AndroidReachingFactsAnalysis(
          apk, icfg, ptaresult, new AndroidModelCallHandler, sp.getSummaryManager, new ClassLoadManager,
          AndroidReachingFactsAnalysisConfig.resolve_static_init,
          timeout = None)
        val idfg = analysis.build(ep, initialfacts, new Context(apk.nameUri))
        val iddResult = InterProceduralDataDependenceAnalysis(apk, idfg)
        val ssm = new DataLeakageAndroidSourceAndSinkManager(AndroidGlobalConfig.settings.sas_file)
        val taint_analysis_result = AndroidDataDependentTaintAnalysis(yard, iddResult, idfg.ptaresult, ssm)
```

Would you please tell me how to get the CFG of inner class?

**Comment by fgwei** [comment]
There is no difference when Amandroid handle outer class and inner class.
In your example, I did not see any inner class.

**Comment by 99zikke** [comment]
I‘m sorry for an ambiguous statement. 
Particularly, the APP's code are as follows:


```
public class MainActivity extends AppCompatActivity {
    ...

    public class MyHandler extends Handler {
        ...
        }

        public void handleMessage(Message msg) {
                         ...something I want to detect
                  }
        }
}
```
And the MainActivity $MyHandler .jawa about the code above are as follows"

```
procedure `void` `handleMessage`(`com.pangu.simplead.MainActivity$MyHandler` v21 @kind this, `android.os.Message` v22 @kind object @name `msg`) @signature `Lcom/pangu/simplead/MainActivity$MyHandler;.handleMessage:(Landroid/os/Message;)V` @AccessFlag PUBLIC {
   ...
   ...something I want to detect...

}
```
However I cannot find them which is in the "Lcom/pangu/simplead/MainActivity$MyHandler" according to the Line Number in the icfg generated by Amandroid.

I'm sorry for delaying your time but I'd be really grateful for your answer!

**Comment by fgwei** [comment]
In your case, it is an implicit call from dispatchMessage() to Handler.handleMessage(). Implicit call is handled specially by ComponentBasedAnalysis. You can check the usage of: https://github.com/arguslab/Argus-SAF/blob/df2557a9654260d5dd933a15f52143bbd6da1f6d/jawa/src/main/scala/org/argus/jawa/flow/interprocedural/IndirectCallResolver.scala#L126

**Comment by 99zikke** [comment]
I’m sorry but could you please tell me more details? My aim is to get the cfg of 

> public void handleMessage(Message msg) 

and I found a scala file named 

> "amandroid/src/main/scala/org/argus/amandroid/alir/componentSummary/ComponentBasedAnalysis.scala"

 which is different from the link you give to me. It makes me confused and the signature in 

> IndirectCallResolver.scala

 is different from mine and I didn't find any examples for how to use it on github. 
So could you please tell me more details about how to get the cfg using IndirectCallResolver.scala?
Thank you very much !

**Comment by 99zikke** [comment]
I‘m sorry but can you kindly help me out?

**Comment by mukut007** [comment]
I think he was referring to using Component based instead of Bottom Up approach which is set as default. You can use -a COMPONENT_BASED for doing component based approach
