### ISSUE TITLE
Unresolved dependencies path

### ISSUE THREAD

**Issue by wonupbi** [arguslab/Argus-SAF#7]
I want to run a example, 'loadAPK', so I add libraryDependencies as 
libraryDependencies += "com.github.arguslab" %% "amandroid-core" % VERSION.

However, when I open sbt interactive mode and try to run this, it fails by unresolved dependencies path.
I think that argus tries to find the dependency in repo1.maven.org/maven2/com/github/arguslab/amandroid-core_2.10 but I find that the version of amandroid is changed into 2.11.

I have no idea to resolve this problem. Any kind of hints will be helpful for me. 

Thank you.

![screenshot from 2016-12-02 17-21-54](https://cloud.githubusercontent.com/assets/24289590/20827232/e1e213d8-b8b3-11e6-9c9a-6513253a7739.png)

**Comment by fgwei** [comment]
This means your scala version should update to 2.11

**Comment by wonupbi** [comment]
thank you I resolved the problem :)
