### ISSUE TITLE
CLI error

### ISSUE THREAD

**Issue by Gunkkk** [arguslab/Argus-SAF#78]
PLATFORM:WSL
 CMD: java -jar  argus-saf_2.12-3.2.0-assembly.jar d *.apk

OUTPUT:                                                                                                                  
[.........                                         ]%19  Downloading amandroid.zip                                                                                                          [..........                                        ]%20z Downloading amandroid.zip                                                                                                          [..................................................]%100 Downloa Downloading amandroid.z... failed!                                                                                         Failed to install amandroid_stash. Please report the issue at our issue tracker: https://github.com/arguslab/Argus-SAF/issues

**Comment by Gunkkk** [comment]
> PLATFORM:WSL
> CMD: java -jar argus-saf_2.12-3.2.0-assembly.jar d *.apk
> 
> OUTPUT:
> [......... ]%19 Downloading amandroid.zip [.......... ]%20z Downloading amandroid.zip [..................................................]%100 Downloa Downloading amandroid.z... failed! Failed to install amandroid_stash. Please report the issue at our issue tracker: https://github.com/arguslab/Argus-SAF/issues

root

**Comment by Gunkkk** [comment]
every i launch it, it will download the amandroid.zip,whcih is very slow, so how can i download it once.

**Comment by irshimul** [comment]
I have faced the same issue. It was probably generated due to scala version inconsistency. I was using a different scala version than 2.12. Later I switched to scala version 2.12 and it was resolved.
