### ISSUE TITLE
Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"

### ISSUE THREAD

**Issue by hpacherkar** [arguslab/Argus-SAF#79]
I am getting this exception while using amandroid as library dependencies. 
libraryDependencies += "com.github.arguslab" % "amandroid_2.12" % "3.2.0"
It takes about an hour downloading the package when i do "sbt run" on a simple project with just a single main.scala.
This is the exception.
Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"

**Comment by irshimul** [comment]
I am also having the exact same problem.

**Comment by irshimul** [comment]
I have solved the issue. It occurred due to scala version inconsistency between my laptop and the amandroid module. Later I switched to scala version 2.12 on my laptop and it was resolved.
