### ISSUE TITLE
Set an entry point

### ISSUE THREAD

**Issue by wonupbi** [arguslab/Argus-SAF#8]
I want draw a call-graph with tutorial example.

val idfg = InterproceduralSuperSpark(global, methods.map(_.getSignature))

but with upper statement, I cannot set the 'methods' value.
How can I set the entry point method?

**Comment by fgwei** [comment]
You can just prepare your methods as the entry point.
To get method you can follow:
http://pag.arguslab.org/argus-saf#tutorial-loadcfm

**Comment by wonupbi** [comment]
I passes that problem but when I try to use toDot method, an error occurs that
'value toDot is not a member of org.argus.jawa.alir.callGraph.CallGraph'.

(even though I try to use prinln(call_graph) to check the value, it fails because of an AssertionError...)

**Comment by fgwei** [comment]
For CallGraph you should use:
call_graph.toSimpleCallGraph(header, outPath, format)

You can check the code in: https://github.com/arguslab/Argus-SAF/blob/master/org.argus.jawa.core/src/main/scala/org/argus/jawa/alir/callGraph/CallGraph.scala

What is the Assertion Error you get?

**Comment by wonupbi** [comment]
the Assertion Error has resolved with re-compiling it.

to use toSimpleCallGraph, should I make xml file?
I try to use it as 'call_graph.toSimpleCallGraph("cfg", "path", "GraphML")
but runtimeException: path/tinkergraph.xml (No such file or directory) has occured.

**Comment by fgwei** [comment]
The path should be a valid existing path.

**Comment by wonupbi** [comment]
yes I set a path as "/home/MYNAME/argus/cfg" or "/home/MYNAME/output_argus/cfg" which are current project directory and output directory respectively. but again, the error occurs
![error](https://cloud.githubusercontent.com/assets/24289590/20956944/5889d23e-bc90-11e6-82f0-6557cba774fc.png)

**Comment by fgwei** [comment]
I see the problem. You outputPath need to set to a separate folder (not exist), otherwise it will try to load it.
This what I do in my code:
val path = outputPath + "/simple_cg"

I will fix this issue in the next version.

**Comment by wonupbi** [comment]
It seems to work. Thank you very much.
