### ISSUE TITLE
Link is broken for argus-saf_***-version-assembly.jar

### ISSUE THREAD

**Issue by hhsamore** [arguslab/Argus-SAF#80]
I wanted to download the "argus-saf_***-version-assembly.jar". But when I click the download it moves to one link and the link for downloading this jar is broken. Could someone can help me with this? Thanks.

**Comment by irshimul** [comment]
Hi, I am also having the same problem. Did you solve it?

**Comment by irshimul** [comment]
I have solved the issue. It occurred due to scala version inconsistency between my laptop and the amandroid module. Later I switched to scala version 2.12 on my laptop and it was resolved.

**Comment by hhsamore** [comment]
Hey,

Yes, I found one link to download this.

Link:
https://web.archive.org/web/20210501193623/https://d29vzk4ow07wi7.cloudfront.net/5cce3983059590b8be2f46633c4d1dd445e3328d36887bcbc983bc8151b910a8?response-content-disposition=attachment%3Bfilename%3D%22argus-saf_2.12-3.1.2-assembly.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNWNjZTM5ODMwNTk1OTBiOGJlMmY0NjYzM2M0ZDFkZDQ0NWUzMzI4ZDM2ODg3YmNiYzk4M2JjODE1MWI5MTBhOD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmFyZ3VzLXNhZl8yLjEyLTMuMS4yLWFzc2VtYmx5LmphciUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYxOTg5ODUwM30sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=rxUBlGWxveOqdqkCcJt3tjBQWFVx1DivtaYtJuuEIXXc--tdtnvAc7z5ud47cknUrzqzz385sH4Ua1sZ47GpXeh7QvoFA-DhiVAo~g-uaHvhMGj45OEJbwnBSlgtIAbTmSEqabg~eEiRRY9n0wmhB5VWfE~HF9HeFAiSxudZT-0Y~yfeU9QX65BE~O43w3L3fZDJZPgScOYdnQi6cfM6JzFc9GrH1L5tAcU4MwxOWRcSiHU-mxy1NRMPHGBJoB27hYA5xCf7n1SMswh0BWo926X3p5-yFxDW6DfLUFD2bgd01EFUtnqg3OFViqtEuG8Ny7ZKWkz48xRcNlDZWhZFug__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA

You can use this to download.
