### ISSUE TITLE
Update site unreachable

### ISSUE THREAD

**Issue by FoelliX** [arguslab/Argus-SAF#85]
Hi,

the update site (https://www.fengguow.dev/resources/... with http or https) seems to be unreachable. Thus, Amandroid always takes a ~2 minute breake before continuing - hindering experiments at scale.

`error: Could not connect to update site.`

Is it correct, that it is unreachable? Will it become reachable again?

**Comment by fgwei** [comment]
Are you use the latest [version](https://github.com/arguslab/Argus-SAF/tree/master/binaries)? It should be reachable, I tested on my device.

**Comment by FoelliX** [comment]
Hi again,

I am also (among others) using the latest version.
I do not know if you changed anything, but anyway this morning everything looks fine again.
The message stopped appearing.

Thanks!

Cheers,
FoelliX
