### ISSUE TITLE
Is there a limitation on APK size?

### ISSUE THREAD

**Issue by wonupbi** [arguslab/Argus-SAF#9]
I try to decompile the Facebook apk file and want to take a list of classes with getComponent_infos in tutorial codes.

When I run it, OutOfMemoryError occurs with Java heap space or GC overhead limit exceeded. Is there a limitation on APK size or Do I have to set any other options?

**Comment by fgwei** [comment]
What's the java heap size you set when you run argus-saf?

**Comment by wonupbi** [comment]
I set the javaOptions as Xmx4G and -XX:-UseGCOverheadLimit

**Comment by ctp27** [comment]
Hi, Im trying to run the tool for taint analysis. I get a Java Heap space error while scanning applications like ACR, Facebook etc. I've tried increasing the heap space for Java but it doesnt work. Is there some other way of going about it?

**Comment by fgwei** [comment]
I test on facebook using:
java -Xms512m -Xmx8g -jar argus-saf-3.0.1-assembly.jar t com.facebook.katana_v119.0.0.23.70-54966242_Android-4.0.3.apk
It finished.

**Comment by ctp27** [comment]
Hey,

I tried it with 8 GB heap space. It gives overhead error after hours of
scanning. Anyway, is there any reason for using apks for Android 4.0.3?
Just curious as to where do you get your apks from. Thanks for your help

Clinton

**Comment by fgwei** [comment]
The 4.0.3 is just something I randomly downloaded from internet. In general if you want to get large volume of apks for research purpose you can visit:
https://androzoo.uni.lu/
http://amd.arguslab.org/
